from crewai import Task
from agents.analyst_agent import create_analyst_agent


get_stock_analysis = Task(
    description=(
        "Perform comprehensive analysis of the stock: {stock}. Use available data sources:\n"
        "1. **Account Information**: Check current account balance, portfolio value, and available investment capacity\n"
        "2. **Stock Price Data**: Get current and extended hours pricing\n"
        "3. **Real-time Quotes**: Use StocksTrader API for current bid/ask spreads\n"
        "4. **News Analysis**: Analyze stock news sentiment and market impact\n"
        "5. **Market Sentiment**: Assess broader market sentiment trends\n"
        "6. **Technical Analysis**: Review technical indicators and chart patterns\n"
        "7. **Research**: Conduct autonomous research for additional insights\n"
        "\n"
        "Provide analysis covering:\n"
        "- **Price Action**: Current price, daily change, volume across trading sessions\n"
        "- **News Sentiment**: Recent news analysis and sentiment impact\n"
        "- **Technical Analysis**: Key indicators and chart patterns\n"
        "- **Market Context**: Broader market and sentiment trends\n"
        "- **Trading Signals**: Combined signals from analysis factors\n"
        "- **Risk Assessment**: Market conditions and volatility factors\n"
        "- **Trading Recommendation**: Specific buy/sell/hold action with reasoning"
    ),
    expected_output=(
        "A comprehensive live trading analysis report including:\n"
        "**ACCOUNT INFORMATION:**\n"
        "- Current account balance and available funds\n"
        "- Portfolio value and investment capacity\n"
        "- Position sizing recommendations based on account size\n"
        "\n"
        "**EXTENDED HOURS ANALYSIS:**\n"
        "- Pre-market and after-hours pricing data\n"
        "- Gap analysis and significance assessment\n"
        "- Volume analysis across all trading sessions\n"
        "- Trading implications and gap strategies\n"
        "- Market status and timing considerations\n"
        "\n"
        "**ENHANCED MARKET DATA ANALYSIS:**\n"
        "- Yahoo Finance: Current price, daily change, volume, extended hours data\n"
        "- StocksTrader API: Real-time bid/ask prices, spreads, liquidity\n"
        "- Data comparison and validation across all sessions\n"
        "- Effective current price determination\n"
        "\n"
        "**COMPREHENSIVE NEWS SENTIMENT ANALYSIS:**\n"
        "- Individual stock sentiment score and trend\n"
        "- Key recent headlines and their impact assessment\n"
        "- Sentiment breakdown (positive/negative/neutral)\n"
        "- Related stocks sentiment context for market correlation\n"
        "- Breaking news alerts and time-sensitive information\n"
        "- News-driven trading implications and timing\n"
        "\n"
        "**TECHNICAL CHART ANALYSIS:**\n"
        "- RSI, MACD, Bollinger Bands analysis across timeframes\n"
        "- Moving averages positioning and trend confirmation\n"
        "- Support and resistance levels with extended hours context\n"
        "- Chart patterns and trend direction analysis\n"
        "- Volume analysis and momentum indicators\n"
        "- Extended hours impact on technical levels\n"
        "\n"
        "**COMPREHENSIVE TRADING SIGNALS:**\n"
        "- Combined signal strength (bullish/bearish/neutral)\n"
        "- Signal confidence level with extended hours considerations\n"
        "- Entry and exit price targets accounting for gaps\n"
        "- Risk management recommendations including gap risks\n"
        "- Position sizing suggestions with volatility adjustments\n"
        "- Stop-loss and take-profit levels across trading sessions\n"
        "\n"
        "**LIVE TRADING RECOMMENDATION:**\n"
        "- Specific action: BUY/SELL/SELL_SHORT/BUY_TO_COVER/HOLD with timing considerations\n"
        "- Rationale based on multi-factor analysis including extended hours\n"
        "- Risk factors including gap risks and market conditions\n"
        "- Time horizon and execution strategy for different market sessions\n"
        "- Market correlation and sector context analysis"
    ),
    agent=create_analyst_agent(),
    max_execution_time=180  # Reduced from 300s for faster execution
)