from crewai import Task
from agents.performance_tracking_agent import create_performance_tracking_agent

performance_analysis_task = Task(
    description=(
        "Analyze comprehensive trading performance for portfolio including stock: {stock}. "
        "Monitor all performance metrics and provide actionable insights:\n"
        "1. **Performance Metrics**: Calculate key performance indicators\n"
        "2. **P&L Analysis**: Detailed profit and loss breakdown\n"
        "3. **Risk-Adjusted Returns**: Calculate Sharpe ratio, Sortino ratio, and alpha\n"
        "4. **Trade Analysis**: Evaluate individual trade performance\n"
        "5. **Win Rate Analysis**: Assess success rate and trade efficiency\n"
        "6. **Drawdown Analysis**: Monitor maximum drawdown and recovery\n"
        "7. **Performance Attribution**: Identify sources of returns\n"
        "8. **Benchmark Comparison**: Compare performance against benchmarks\n"
        "9. **Extended Hours Impact**: Analyze extended hours trading performance\n"
        "10. **Performance Optimization**: Identify improvement opportunities\n"
        "\n"
        "**PERFORMANCE ANALYSIS FRAMEWORK:**\n"
        "- Total return calculation and breakdown\n"
        "- Risk-adjusted metrics (Sharpe, Sortino, Calmar ratios)\n"
        "- Maximum drawdown and recovery analysis\n"
        "- Win rate and profit factor calculation\n"
        "- Average win/loss ratio analysis\n"
        "- Performance attribution by position/sector\n"
        "- Benchmark comparison (S&P 500, sector indices)\n"
        "- Extended hours performance impact assessment\n"
        "- News sentiment correlation with performance\n"
        "- Trade execution quality analysis"
    ),
    expected_output=(
        "A comprehensive performance analysis report including:\n"
        "**OVERALL PERFORMANCE METRICS:**\n"
        "- Total return and time-weighted return\n"
        "- Risk-adjusted returns (Sharpe, Sortino, Calmar ratios)\n"
        "- Maximum drawdown and current drawdown\n"
        "- Volatility and beta analysis\n"
        "- Alpha generation and tracking error\n"
        "\n"
        "**TRADE ANALYSIS:**\n"
        "- Win rate and profit factor\n"
        "- Average win/loss amounts and ratios\n"
        "- Best and worst performing trades\n"
        "- Trade duration analysis\n"
        "- Success rate by position size\n"
        "\n"
        "**PERFORMANCE ATTRIBUTION:**\n"
        "- Performance by individual positions\n"
        "- Sector contribution analysis\n"
        "- Asset allocation impact\n"
        "- Extended hours trading contribution\n"
        "- News sentiment impact on performance\n"
        "\n"
        "**BENCHMARK COMPARISON:**\n"
        "- Performance vs S&P 500 and relevant indices\n"
        "- Relative performance analysis\n"
        "- Risk-adjusted outperformance\n"
        "- Performance consistency metrics\n"
        "\n"
        "**PERFORMANCE OPTIMIZATION RECOMMENDATIONS:**\n"
        "- Strategy improvement suggestions\n"
        "- Risk management enhancements\n"
        "- Position sizing optimization\n"
        "- Timing improvement opportunities\n"
        "- Performance monitoring enhancements"
    ),
    agent=create_performance_tracking_agent(),
    max_execution_time=180  # Reduced from 300s for faster execution
) 