from crewai import Task
from agents.trader_agent import create_trader_agent

trade_decision = Task(
    description=(
        "PROVIDE EXECUTION-READY TRADING RECOMMENDATIONS for {stock} that will be AUTOMATICALLY EXECUTED "
        "by the system. Your recommendations will be immediately parsed and executed, so provide clear, "
        "specific trading instructions with exact quantities, prices, and risk management parameters. "
        "Follow this systematic process:\n"
        "1. **Account Assessment**: Check account information, balance, and current positions\n"
        "2. **Extended Hours Analysis**: Analyze pre-market and after-hours activity, gaps, and implications\n"
        "3. **Real-time Data**: Get current real-time quotes and market data across all sessions\n"
        "4. **Enhanced News Analysis**: Analyze recent news sentiment, breaking news, and market context\n"
        "5. **Market Context Analysis**: Assess related stocks sentiment and sector analysis for correlation\n"
        "6. **Technical Analysis**: Review technical indicators, patterns, and signals with extended hours context\n"
        "7. **Risk Assessment**: Evaluate market conditions, volatility, gap risks, and extended hours factors\n"
        "8. **Trading Decision**: Make informed BUY/SELL/HOLD decision with specific quantities and prices\n"
        "9. **Execution Instructions**: Provide clear trading instructions that will be automatically executed\n"
        "10. **Risk Management**: Specify stop losses, take profits, and position sizing with gap considerations\n"
        "11. **Verification**: Confirm recommendation format for automatic execution\n"
        "\n"
        "**EXECUTION-READY GUIDELINES:**\n"
        "- Format recommendations clearly: 'BUY [SYMBOL] [QUANTITY] shares at [PRICE]' or 'SELL [SYMBOL] [QUANTITY] shares at [PRICE]'\n"
        "- Include specific position sizes and exact quantities\n"
        "- Specify stop losses and take profits with exact prices\n"
        "- Maximum position size: 10% of available capital\n"
        "- Always include stop losses (3-5% below entry for long positions, 3-5% above entry for short positions)\n"
        "- Set take profits based on technical resistance levels and extended hours context\n"
        "- Consider news sentiment and breaking news in timing decisions\n"
        "- Account for pre-market and after-hours gaps in risk calculations\n"
        "- Verify technical signals across all trading sessions before recommending execution\n"
        "- Account for bid-ask spreads and extended hours liquidity in order pricing\n"
        "- Monitor related stocks sentiment for market correlation risks\n"
        "- Adjust position sizing based on extended hours volatility\n"
        "- IMPORTANT: StocksTrader API - Use 'buy' order to go long, 'sell' order to go short. To close positions use close_position(deal_id)!"
    ),
    expected_output=(
        "A comprehensive EXECUTION-READY trading recommendation report including:\n"
        "**ACCOUNT STATUS:**\n"
        "- Current account balance and available capital\n"
        "- Existing positions and their P&L\n"
        "- Available margin and buying power\n"
        "\n"
        "**EXTENDED HOURS ANALYSIS:**\n"
        "- Pre-market and after-hours pricing analysis\n"
        "- Gap analysis and significance assessment\n"
        "- Extended hours volume and liquidity analysis\n"
        "- Trading implications and gap strategies\n"
        "- Market session timing considerations\n"
        "\n"
        "**ENHANCED MARKET ANALYSIS:**\n"
        "- Real-time quote data and bid-ask spreads across sessions\n"
        "- Current market conditions and volatility including extended hours\n"
        "- Enhanced news sentiment impact on decision with breaking news alerts\n"
        "- Related stocks sentiment and market correlation analysis\n"
        "- Technical signals confirmation with extended hours context\n"
        "\n"
        "**TRADING DECISION:**\n"
        "- Final decision: BUY/SELL/SELL_SHORT/BUY_TO_COVER/HOLD with enhanced rationale\n"
        "- Entry price target and reasoning with gap considerations\n"
        "- Position size calculation and risk percentage adjusted for volatility\n"
        "- Multi-factor enhanced analysis summary including extended hours\n"
        "- Market timing and session-specific considerations\n"
        "- Order side specification: 'buy', 'close', 'sell_short', or 'close'\n"
        "\n"
        "**ORDER EXECUTION (if trading):**\n"
        "- Order type (market/limit) and reasoning with session considerations\n"
        "- Exact order details (symbol, quantity, price) with gap adjustments\n"
        "- Stop loss and take profit levels accounting for extended hours\n"
        "- Order ID and confirmation status\n"
        "- Execution price and slippage analysis\n"
        "\n"
        "**ENHANCED RISK MANAGEMENT:**\n"
        "- Risk percentage of total capital with volatility adjustments\n"
        "- Stop loss placement and rationale including gap risks\n"
        "- Take profit targets and exit strategy across trading sessions\n"
        "- Position monitoring plan with extended hours considerations\n"
        "- Risk mitigation measures implemented for gap and correlation risks\n"
        "- Market correlation and sector risk assessment"
    ),
    agent=create_trader_agent(),
    max_execution_time=300
)